= Spin Spong

== Introduction

Qu’est-ce qu’un jeu vidéo::

Qu’est-ce qu’un moteur de jeu-vidéo::

* logiciel qui facilite le développement de jeux
* manipulation d’image facilité
* manipulation de son
* gestion avancée des évènements (claviers, souris, manettes…)
* éventuellement accessible pour des personnes qui ne dév pas

Godot par rapport aux autres moteurs::

* logiciel libre
* assez vieux, code libre récemment
* facile à prendre en main
* développement actif
* gain en popularité

d’autres moteurs populaires sont :

* Unity
* Unreal engine
* GameMaker
* …

Un lien temporaire d’une https://drop.chapril.org/download/0c86a17d991def93/#vsvwF9FUE0mhO_A3cgI8Fw[vidéo du jeu].

== Lecture de code

== Mob programming

Kékéçé le
https://fr.wikipedia.org/wiki/Programmation_en_groupe[mob programming] ?

Dans le cadre de la session de code collective, nous proposons des objectifs réalisables::

* Utiliser l’instanciation de nodes pour implémenter un effet de particule.
* Utiliser les nodes d’animation pour implémenter l’animation d’une couronne (déjà faite) en fin de partie.
* Utiliser les nodes de gestion de son pour implémenter des effets sonores pour les impacts de la balle.
* Utiliser l’« observer pattern » pour donner différentes vitesses à la balle en fonction du mouvement de la paddle.

NOTE: Il s’agit là de propositions, d’autres choses sont possibles et accessibles.

On discute brièvement (5min?) des options que l’on a (même celles qui ne sont pas dans cette liste!) et on choisit un objectif que l’on prend pour cette session.

=== Déroulement

. Faire un fork du projet sur `adatechschool` pour que tout le monde puisse y `push`.
. Une personne partage son écran, les autres lui disent quoi faire.
. On change régulièrement la personne qui partage son écran (10-15min?).
. L’objectif est de coder tout·es ensemble sur la même fonctionnalité.
. Si on ne finit pas l’objectif avant la fin de la session, ce n’est pas grave.
. On prend garde à répondre aux questions de tout·es et laisser chacun·e essayer ses idées.
. Créer une `pull request` de `adatechschool/spin-spong` vers `Leirda01/spin-spong`.
